// Core colors
const COLOR_CORE_BRAND = '#007FA3'
const COLOR_CORE_LIGHT = '#FFFFFF'
const COLOR_CORE_DARK = '#000000'
const COLOR_CORE_PRIMARY = '#003057'
const COLOR_CORE_SECONDARY = '#D4EAE4'
const COLOR_CORE_TERTIARY = '#505759'
const COLOR_CORE_QUATERNARY = '#D2DB0E'

// Alternate colors
const COLOR_SUPPORTING_PRIMARY = '#005A70'
const COLOR_SUPPORTING_SECONDARY = '#008638'

// Notifications & call to action colors
const COLOR_ACCENT_YELLOW = '#FFB81C'
const COLOR_ACCENT_ORANGE = '#EA7600'
const COLOR_ACCENT_RED = '#DB0020'
const COLOR_ACCENT_TURQOISE = '#12B2A6'
const COLOR_ACCENT_PURPLE = '#9E007E'
const COLOR_ACCENT_PINK = '#EA067E'
const COLOR_ACCENT_GREEN = '#84BD00'

// Background
const COLOR_TINT_LIGHTER = '#EDEDED'
const COLOR_TINT_LIGHT = '#CCCCCC'
const COLOR_TINT_DARK = '#999999'
const COLOR_TINT_DARKER = '#666666'

// Text colors
const COLOR_HEADING = COLOR_CORE_PRIMARY
const COLOR_TEXT_PRIMARY = COLOR_CORE_DARK
const COLOR_TEXT_SECONDARY = COLOR_TINT_DARKER
const COLOR_LINK = COLOR_CORE_BRAND

// Levels
const COLOR_LEVEL_1 = COLOR_ACCENT_TURQOISE
const COLOR_LEVEL_2 = COLOR_ACCENT_ORANGE
const COLOR_LEVEL_3 = COLOR_ACCENT_PINK
const COLOR_LEVEL_4 = COLOR_ACCENT_RED

// Activities
const COLOR_CARD_UNSELECTED = '#E9fAFF'
const COLOR_CARD_SELECTED = COLOR_CORE_PRIMARY

// Messages
const COLOR_TICK_UNSELECTED = '#ADBCC8'

// Cloudinary placeholders
const COLOR_CLOUDINARY_PLACEHOLDER = '#127FA1'

export {
	COLOR_CORE_BRAND,
	COLOR_CORE_LIGHT,
	COLOR_CORE_DARK,
	COLOR_CORE_PRIMARY,
	COLOR_CORE_SECONDARY,
	COLOR_CORE_TERTIARY,
	COLOR_CORE_QUATERNARY,

	COLOR_SUPPORTING_PRIMARY,
	COLOR_SUPPORTING_SECONDARY,

	COLOR_ACCENT_YELLOW,
	COLOR_ACCENT_ORANGE,
	COLOR_ACCENT_RED,
	COLOR_ACCENT_TURQOISE,
	COLOR_ACCENT_PURPLE,
	COLOR_ACCENT_PINK,
	COLOR_ACCENT_GREEN,

	COLOR_TINT_LIGHTER,
	COLOR_TINT_LIGHT,
	COLOR_TINT_DARK,
	COLOR_TINT_DARKER,

	COLOR_HEADING,
	COLOR_TEXT_PRIMARY,
	COLOR_TEXT_SECONDARY,
	COLOR_LINK,

	COLOR_LEVEL_1,

	COLOR_CARD_UNSELECTED,
	COLOR_CARD_SELECTED,

	COLOR_TICK_UNSELECTED,

	COLOR_CLOUDINARY_PLACEHOLDER,
}
