import { createTypes } from 'reduxsauce'

export default createTypes(`
	GET_CONTACTS_ATTEMPT
	GET_CONTACTS_SUCCESS
	GET_CONTACTS_FAILURE
	UPDATE_COMMUNITY_SETTINGS_ATTEMPT
	UPDATE_COMMUNITY_SETTINGS_SUCCESS

	SEARCH_COMMUNITY_ATTEMPT
	SEARCH_COMMUNITY_SUCCESS
	SEARCH_COMMUNITY_FAILURE
	CLEAR_COMMUNITY_SEARCH

	SET_ACTIVE_CONNECTION_ID
	UNSET_ACTIVE_CONNECTION_ID
	MANAGE_CONNECTION_ATTEMPT
	MANAGE_CONNECTION_SUCCESS
	MANAGE_CONNECTION_FAILURE
`)
